/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as ClientRegisterRouteImport } from './routes/client/Register'
import { Route as ClientLoginRouteImport } from './routes/client/Login'
import { Route as ClientCartRouteImport } from './routes/client/Cart'
import { Route as BakeryRegisterRouteImport } from './routes/bakery/Register'
import { Route as BakeryOrdersRouteImport } from './routes/bakery/Orders'
import { Route as BakeryLoginRouteImport } from './routes/bakery/Login'
import { Route as BakeryDashboardRouteImport } from './routes/bakery/Dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRegisterRoute = ClientRegisterRouteImport.update({
  id: '/client/Register',
  path: '/client/Register',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/Login',
  path: '/client/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCartRoute = ClientCartRouteImport.update({
  id: '/client/Cart',
  path: '/client/Cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryRegisterRoute = BakeryRegisterRouteImport.update({
  id: '/bakery/Register',
  path: '/bakery/Register',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryOrdersRoute = BakeryOrdersRouteImport.update({
  id: '/bakery/Orders',
  path: '/bakery/Orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryLoginRoute = BakeryLoginRouteImport.update({
  id: '/bakery/Login',
  path: '/bakery/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryDashboardRoute = BakeryDashboardRouteImport.update({
  id: '/bakery/Dashboard',
  path: '/bakery/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bakery/Dashboard': typeof BakeryDashboardRoute
  '/bakery/Login': typeof BakeryLoginRoute
  '/bakery/Orders': typeof BakeryOrdersRoute
  '/bakery/Register': typeof BakeryRegisterRoute
  '/client/Cart': typeof ClientCartRoute
  '/client/Login': typeof ClientLoginRoute
  '/client/Register': typeof ClientRegisterRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bakery/Dashboard': typeof BakeryDashboardRoute
  '/bakery/Login': typeof BakeryLoginRoute
  '/bakery/Orders': typeof BakeryOrdersRoute
  '/bakery/Register': typeof BakeryRegisterRoute
  '/client/Cart': typeof ClientCartRoute
  '/client/Login': typeof ClientLoginRoute
  '/client/Register': typeof ClientRegisterRoute
  '/client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bakery/Dashboard': typeof BakeryDashboardRoute
  '/bakery/Login': typeof BakeryLoginRoute
  '/bakery/Orders': typeof BakeryOrdersRoute
  '/bakery/Register': typeof BakeryRegisterRoute
  '/client/Cart': typeof ClientCartRoute
  '/client/Login': typeof ClientLoginRoute
  '/client/Register': typeof ClientRegisterRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bakery/Dashboard'
    | '/bakery/Login'
    | '/bakery/Orders'
    | '/bakery/Register'
    | '/client/Cart'
    | '/client/Login'
    | '/client/Register'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bakery/Dashboard'
    | '/bakery/Login'
    | '/bakery/Orders'
    | '/bakery/Register'
    | '/client/Cart'
    | '/client/Login'
    | '/client/Register'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/bakery/Dashboard'
    | '/bakery/Login'
    | '/bakery/Orders'
    | '/bakery/Register'
    | '/client/Cart'
    | '/client/Login'
    | '/client/Register'
    | '/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BakeryDashboardRoute: typeof BakeryDashboardRoute
  BakeryLoginRoute: typeof BakeryLoginRoute
  BakeryOrdersRoute: typeof BakeryOrdersRoute
  BakeryRegisterRoute: typeof BakeryRegisterRoute
  ClientCartRoute: typeof ClientCartRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientRegisterRoute: typeof ClientRegisterRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/Register': {
      id: '/client/Register'
      path: '/client/Register'
      fullPath: '/client/Register'
      preLoaderRoute: typeof ClientRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/Login': {
      id: '/client/Login'
      path: '/client/Login'
      fullPath: '/client/Login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/Cart': {
      id: '/client/Cart'
      path: '/client/Cart'
      fullPath: '/client/Cart'
      preLoaderRoute: typeof ClientCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery/Register': {
      id: '/bakery/Register'
      path: '/bakery/Register'
      fullPath: '/bakery/Register'
      preLoaderRoute: typeof BakeryRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery/Orders': {
      id: '/bakery/Orders'
      path: '/bakery/Orders'
      fullPath: '/bakery/Orders'
      preLoaderRoute: typeof BakeryOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery/Login': {
      id: '/bakery/Login'
      path: '/bakery/Login'
      fullPath: '/bakery/Login'
      preLoaderRoute: typeof BakeryLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery/Dashboard': {
      id: '/bakery/Dashboard'
      path: '/bakery/Dashboard'
      fullPath: '/bakery/Dashboard'
      preLoaderRoute: typeof BakeryDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BakeryDashboardRoute: BakeryDashboardRoute,
  BakeryLoginRoute: BakeryLoginRoute,
  BakeryOrdersRoute: BakeryOrdersRoute,
  BakeryRegisterRoute: BakeryRegisterRoute,
  ClientCartRoute: ClientCartRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientRegisterRoute: ClientRegisterRoute,
  ClientIndexRoute: ClientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
